//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uchetProject.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class uchotDBEntities : DbContext
    {
        public uchotDBEntities()
            : base("name=uchotDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Группы> Группы { get; set; }
        public virtual DbSet<Заявки> Заявки { get; set; }
        public virtual DbSet<Преподаватель> Преподаватель { get; set; }
        public virtual DbSet<Сотрудник> Сотрудник { get; set; }
        public virtual DbSet<Специальность> Специальность { get; set; }
        public virtual DbSet<Статус_заявки> Статус_заявки { get; set; }
        public virtual DbSet<Статус_студента> Статус_студента { get; set; }
        public virtual DbSet<Студент> Студент { get; set; }
        public virtual DbSet<Тип_сотрудника> Тип_сотрудника { get; set; }
        public virtual DbSet<Форма_обучения> Форма_обучения { get; set; }
    }
}
