//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uchetProject.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Группы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Группы()
        {
            this.Студент = new HashSet<Студент>();
        }
    
        public int ID { get; set; }
        public int ID_Специальность { get; set; }
        public int Места { get; set; }
        public int Свободные_места { get; set; }
        public string Префикс { get; set; }
        public int Курс { get; set; }
        public System.DateTime Дата_создания { get; set; }
        public Nullable<System.DateTime> Дата_окончания { get; set; }
        public Nullable<int> ID_Преподаватель { get; set; }
    
        public virtual Преподаватель Преподаватель { get; set; }
        public virtual Специальность Специальность { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Студент> Студент { get; set; }
    }
}
