//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uchetProject.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Студент
    {
        public int ID { get; set; }
        public string ФИО { get; set; }
        public System.DateTime Дата_рождения { get; set; }
        public int ID_Группа { get; set; }
        public int ID_Статус { get; set; }
        public int ID_Форма { get; set; }
        public System.DateTime Зачисление { get; set; }
        public Nullable<System.DateTime> Выбытие { get; set; }
        public string Номер { get; set; }
        public string Изображение { get; set; }
    
        public virtual Группы Группы { get; set; }
        public virtual Статус_студента Статус_студента { get; set; }
        public virtual Форма_обучения Форма_обучения { get; set; }
    }
}
